basePath: /api/v1
definitions:
  handler.errorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  model.Message:
    properties:
      id:
        type: integer
      message:
        type: string
      status:
        type: string
    type: object
  model.MessageCreate:
    properties:
      message:
        type: string
    type: object
host: mini.eridani.site
info:
  contact: {}
  description: This is mini server
  title: mini server
  version: "1.0"
paths:
  /api/v1/create:
    post:
      consumes:
      - application/json
      description: Add message to DB
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.MessageCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Message'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Create message
  /api/v1/getMessages:
    get:
      consumes:
      - application/json
      description: Get messages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Message'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Get all messages
schemes:
- http
- https
swagger: "2.0"
